apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /mnt/data/laravel
  storageClassName: laravel-pv